apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kiali-ingress
  namespace: {{ .Release.Namespace }}
  annotaions:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/kiali"
        backend:
          service:
            name: kiali
            port:
              number: 20001
