{{- if .Values.x }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali-ingress
  namespace: {{ .Values.operator.cr.namespace }}
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/kiali"
        backend:
          service:
            name: kiali
            port:
              number: 20001
{{- end }}
