apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo
  labels:
    argo.okmvp.internal/category: operator
spec:
  project: default
  source:
    repoURL: {{ .Values.repository }}
    targetRevision: {{ .Values.revision }}
    path: helm/operator/argo/
    helm:
      parameters:
      - name:  cd.server.ingress.annotations.kubernetes\.io\/ingress\.class
        value: {{ .Values.network.ingress.type }}
      - name:  cd.server.ingress.hosts[0]
        value: argo.{{ .Values.domain }}
      {{- if eq .Values.network.ingress.type "istio" }}
      - name:  cd.server.ingress.paths[0]
        value: "/*"
      {{- end }}
      - name:  cd.server.config.url
        value: http://argo.{{ .Values.domain }}
      valueFiles:
      - values.yaml
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
