apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo
  labels:
    argo.okmvp.internal/category: operator
spec:
  project: default
  source:
    repoURL: {{ .Values.repository }}
    targetRevision: {{ .Values.revision }}
    path: helm/operator/argo/
    helm:
      parameters:
      - name:  cd.server.ingress.hosts[0]
        value: argo.{{ .Values.domain }}
      - name:  cd.server.config.url
        value: http://argo.{{ .Values.domain }}
      - name:  apps.revision
        value: {{ .Values.revision }}
      - name:  apps.domain
        value: {{ .Values.domain }}
      - name:  apps.metallb.addresses
        value: {{ .Values.metallb.addresses }}
      valueFiles:
      - values.yaml
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
