apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/bitnami/charts
- name: metallb
  version: 2.3.5
  repository: https://charts.bitnami.com/bitnami/
