---
server:
  extraArgs:
  - --insecure
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - ""
  config:
    url: ""
    repositories: |
      - url: https://github.com/ghilbut/byfs-modules.git
