apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo
  labels:
    argo.okmvp.internal/category: network
spec:
  project: default
  source:
    repoURL: https://github.com/okmvp/docker-desktop-k8s.git
    targetRevision: feature/metallb
    path: helm/network/metallb
    helm:
      valueFiles:
      - values.yaml
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
