
domain: okmvp.internal

repository: https://github.com/okmvp/docker-desktop-k8s.git
revision:   main

metallb:
  addresses: ""

kafka:
  zookeeper:
    persistence:
      dataDirPath: ""
      dataDirSize: 1Gi
      dataLogDirPath: ""
      dataLogDirSize: 4Gi
  kafka:
    persistence:
      path: ""
      size: 4Gi
