
domain: okmvp.internal

repository: https://github.com/okmvp/docker-desktop-k8s.git
revision:   main

network:
  gateway:
    type: nginx  # nginx, istio(progress), consul(todo), haproxy(todo)

  metallb:
    addresses: ""

data:
  kafka:
    enabled: false
