apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/kubernetes/ingress-nginx//charts/ingress-nginx
- name: ingress-nginx
  version: 3.29.0
  repository: https://kubernetes.github.io/ingress-nginx/
  alias: nginx
