apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/okmvp/docker-desktop-k8s.git
    targetRevision: feature/argo-by-argo
    path: helm/operator/argo/
    helm:
      parameters:
      - name:  cd.server.ingress.hosts[0]
        value: {{ .Values.cd.server.ingress.hosts[0] }}
      - name:  cd.server.config.url
        value: {{ .Values.cd.server.config.url }}
      valueFiles:
      - values.yaml
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
